# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-PObject
version:      2.03
version_from: PObject.pm
installdirs:  site
requires:
    File::Spec:                    0
    IO::Dir:                       0
    Log::Agent:                    0
    Storable:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
